name: build

on: [push, pull_request]
jobs:
  build-source:
    runs-on: ubuntu-latest
    steps:
      - name: 'pull repo'
        uses: actions/checkout@v2
      - run: chmod +x build.sh && ./build.sh